# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
      - 'mona/octocat'
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build and extract typescript interfaces
        working-directory: ./lib
        run: |
           npm ci
           npm npm run gen-api
           npm build
           npm build:types
           
  version:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        - name: Publish package to NPM
          working-directory: ./lib
          run: |
            git config --global user.name 'RAORelewise'
            git config --global user.email 'rao@relewise.com'
            npm version patch -m "[RELEASE] %s"
            git push

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Publish package to NPM
        working-directory: ./lib
        run: |
           npm ci
           npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
