name: dispatch receiver

on: [repository_dispatch]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Bump version
        working-directory: ./lib
        run: |
          git config --global user.name 'RAORelewise'
          git config --global user.email 'rao@relewise.com'
          npm version patch -m "[RELEASE] %s"
          git push
