name: Version and NPM publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New package version'
        required: false

concurrency: # prevent concurrent releases
  group: npm-bump
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build and extract typescript interfaces
        run: |
           npm ci
           npm run gen-api
           npm run build
           npm run build:types
           
  publish:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Bump version
        run: |
          git config --global user.name 'RAORelewise'
          git config --global user.email 'rao@relewise.com'
          npm version patch
          git add package.json
          git commit -m 'bump version'
          git push

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@rao_relewise_worker'
      - name: Publish package to NPM
        run: |
           npm ci
           npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
