name: dispatch receiver

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New package version'
        required: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Bump version
        working-directory: ./lib
        run: |
          git config --global user.name 'RAORelewise'
          git config --global user.email 'rao@relewise.com'
          npm version patch -m "[RELEASE] %s"
          git add package.json
          git push
